# Generated by Django 4.1.5 on 2023-01-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50, verbose_name='Nome do Produto')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('valor_bruto', models.FloatField(verbose_name='Valor Bruto')),
                ('valor_liquido', models.FloatField(verbose_name='Valor Líquido')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
