# Generated by Django 4.1.5 on 2023-01-28 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('stock', '0002_produto_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nota fiscal')),
                ('movimento', models.CharField(blank=True, choices=[('E', 'Entrada'), ('S', 'Saida')], max_length=1)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-criado',),
            },
        ),
        migrations.CreateModel(
            name='ItensEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('saldo', models.PositiveIntegerField(blank=True)),
                ('estoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='stock.estoque')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.produto')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.CreateModel(
            name='EstoqueEntrada',
            fields=[
            ],
            options={
                'verbose_name': 'Estoque Entrada',
                'verbose_name_plural': 'Estoque Entrada',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.estoque',),
        ),
        migrations.CreateModel(
            name='EstoqueSaida',
            fields=[
            ],
            options={
                'verbose_name': 'Estoque Saida',
                'verbose_name_plural': 'Estoque Saida',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.estoque',),
        ),
    ]
