# Generated by Django 4.1.5 on 2023-01-28 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=128, unique=True, verbose_name='Categoria')),
            ],
            options={
                'ordering': ('categoria',),
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50, verbose_name='Nome do Produto')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('estoque', models.IntegerField(default=0, verbose_name='Estoque')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor Bruto')),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor Líquido')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.categoria')),
            ],
            options={
                'ordering': ('nome_produto',),
            },
        ),
    ]
